name: Conty CI

on:
  schedule:
    - cron:  '0 0 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: 'false'

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: utils.yml
          workflow_conclusion: success
          if_no_artifact_found: ignore
          path: /opt

      - name: Build Conty
        run: |
          if [ -f /opt/Utils/utils.tar.gz ]; then
              cp /opt/Utils/* .
          fi

          chmod +x create-arch-bootstrap.sh create-conty.sh
          sudo ./create-arch-bootstrap.sh && ./create-conty.sh

      - name: Split conty.sh if needed
        run: |
          mkdir -p split
          if [ "$(stat -c%s conty.sh)" -ge $((3 * 1024 * 1024 * 1024)) ]; then
              split -b 2G conty.sh split/conty.part.
          else
              cp conty.sh split/conty.part.a
          fi

      - name: Upload split artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Conty-Split
          path: split/
